[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
vectorbase = {path = "../../", version = "0.0.1"}
galois = {path = "../../../galois", version = "0.1.0"}
rand = "0.8.5"
tokio = {version ="1.40.0",features = ["full"]}
